# Time in seconds before the server restarts
restart-time-seconds: 43200

# Command to execute when the time runs out
restart-command: "restart"

warning-times-seconds:
  - 3600
  - 1800
  - 600
  - 300
  - 60
  - 30
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1

# Warning in Action Bar for the last few seconds
action-bar-countdown: true
action-bar-starts-at: 10

messages:
  # Warning message (Use %time% for formatted time)
  warning: "&8[&#FF3333&lRUMAH KITA&8] &7Server will restart in &#FFC000%time%&7!"
  
  # Message when the server shuts down
  restarting: "&8[&#FF3333&lRUMAH KITA&8] &#FF5555Saving data and restarting server now..."
  
  # Kick reason message
  kick-message: "&#FF3333&lSERVER RESTARTING!\n\n&7Please wait a few minutes\n&7and rejoin the server."

# Large screen text alerts (Title & Subtitle)
title-alerts:
  enabled: true
  title: "&#FF3333&lSERVER &f&lRESTART"
  subtitle: "&7Restarting in &#FFC000%time%&7!"

# Sound effects when warnings appear
sounds:
  enabled: true
  warning-sound: "BLOCK_NOTE_BLOCK_PLING"
  restart-sound: "ENTITY_ENDER_DRAGON_GROWL"
