name: AutoRestart
version: '1.0'
main: dev.rumahkita.autorestart.AutoRestartPlugin
api-version: '1.13'
commands:
  autorestart:
    description: Check restart time or reload config.
    aliases: [ar]
permissions:
  autorestart.admin:
    description: Allows the use of the autorestart command.
    default: op
